# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{caty}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fabian Streitel"]
  s.date = %q{2009-09-08}
  s.description = %q{Caty is a command line parser that maps arguments to instance methods}
  s.email = %q{karottenreibe@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.markdown"
  ]
  s.files = [
    "HISTORY.markdown",
     "LICENSE.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "caty.gemspec",
     "lib/caty.rb",
     "lib/caty/converters.rb",
     "lib/caty/errors.rb",
     "lib/caty/global_option.rb",
     "lib/caty/has_description.rb",
     "lib/caty/help_system.rb",
     "lib/caty/helpers.rb",
     "lib/caty/indirection.rb",
     "lib/caty/option.rb",
     "lib/caty/option_array.rb",
     "lib/caty/option_constructor.rb",
     "lib/caty/task.rb",
     "lib/caty/task_hash.rb",
     "test/kitty.rb",
     "test/test_caty.rb",
     "test/test_option.rb",
     "test/test_option_array.rb",
     "test/test_structure.rb",
     "test/test_task.rb"
  ]
  s.homepage = %q{http://github.com/karottenreibe/caty}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{k-gems}
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Caty is a command line parser that maps arguments to instance methods}
  s.test_files = [
    "test/kitty.rb",
     "test/test_caty.rb",
     "test/test_option.rb",
     "test/test_option_array.rb",
     "test/test_structure.rb",
     "test/test_task.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ohash>, [">= 0"])
    else
      s.add_dependency(%q<ohash>, [">= 0"])
    end
  else
    s.add_dependency(%q<ohash>, [">= 0"])
  end
end
